env                               = "prod"
region                            = "us-east-1"
aws_account_number                = "332281781429"
kms_key_arn_for_dms               = "arn:aws:kms:us-east-1:332281781429:key/f786e3aa-7612-40da-aafa-dd21b2ab2e1d"
replication_subnet_group_id       = "default-vpc-ed4b2288"
dms_vpc_security_group_id         = "sg-0394c6d99a53ba9a7"
dms_instance_storage              = 200
source_endpoint_arn               = "arn:aws:dms:us-east-1:332281781429:endpoint:MYMJ3KPIC7ZOV7CWY6M4ZNCXXA"
dms_instance_class                = "dms.c5.2xlarge"
dms_security_group                = "sg-0394c6d99a53ba9a7"
sqs_queue_name                    = ["omni-wt-rt-shipment-header-queue-prod", "omni-wt-rt-shipment-apar-queue-prod", "omni-wt-rt-references-queue-prod", "omni-wt-rt-shipper-queue-prod", "omni-wt-rt-consignee-queue-prod", "omni-wt-rt-shipment-milestone-queue-prod", "omni-wt-rt-apar-failure-queue-prod", "omni-wt-rt-shipment-desc-prod", "omni-wt-rt-customers-prod", "omni-wt-rt-instructions-prod", "omni-wt-rt-users-prod", "omni-wt-rt-charge-cost-code-prod", "omni-wt-rt-consol-stop-items-prod", "omni-wt-rt-consol-stop-headers-prod", "omni-wt-rt-confirmation-cost-prod", "omni-wt-rt-zip-codes-prod", "omni-wt-rt-timezone-master-prod", "omni-wt-rt-timezone-zip-cr-prod", "omni-wt-rt-tracking-notes-prod"]
sqs_deadletter_queue_name         = ["omni-wt-rt-shipment-header-DLQ-prod", "omni-wt-rt-shipment-apar-DLQ-prod", "omni-wt-rt-references-DLQ-prod", "omni-wt-rt-shipper-DLQ-prod", "omni-wt-rt-consignee-DLQ-prod", "omni-wt-rt-shipment-milestone-DLQ-prod", "omni-wt-rt-apar-failure-DLQ-prod", "omni-wt-rt-shipment-desc-DLQ-prod", "omni-wt-rt-customers-DLQ-prod", "omni-wt-rt-instructions-DLQ-prod", "omni-wt-rt-users-DLQ-prod", "omni-wt-rt-charge-cost-code-DLQ-prod", "omni-wt-rt-consol-stop-items-DLQ-prod", "omni-wt-rt-consol-stop-headers-DLQ-prod", "omni-wt-rt-confirmation-cost-DLQ-prod", "omni-wt-rt-zip-codes-DLQ-prod", "omni-wt-rt-timezone-master-DLQ-prod", "omni-wt-rt-timezone-zip-cr-DLQ-prod", "omni-wt-rt-tracking-notes-DLQ-prod"]
sqs_queue_arn_ssm_name            = ["/omni-wt-rt-updates/prod/shipment-header/queue.arn", "/omni-wt-rt-updates/prod/shipment-apar/queue.arn", "/omni-wt-rt-updates/prod/references/queue.arn", "/omni-wt-rt-updates/prod/shipper/queue.arn", "/omni-wt-rt-updates/prod/consignee/queue.arn", "/omni-wt-rt-updates/prod/shipment-milestone/queue.arn", "/omni-wt-rt-updates/prod/apar-failure/queue.arn", "/omni-wt-rt-updates/prod/shipment-desc/queue.arn", "/omni-wt-rt-updates/prod/customers/queue.arn", "/omni-wt-rt-updates/prod/instructions/queue.arn", "/omni-wt-rt-updates/prod/users/queue.arn", "/omni-wt-rt-updates/prod/charge-cost-code/queue.arn", "/omni-wt-rt-updates/prod/consol-stop-items/queue.arn", "/omni-wt-rt-updates/prod/consol-stop-headers/queue.arn", "/omni-wt-rt-updates/prod/confirmation-cost/queue.arn", "/omni-wt-rt-updates/prod/zip-codes/queue.arn", "/omni-wt-rt-updates/prod/timezone-master/queue.arn", "/omni-wt-rt-updates/prod/timezone-zip-cr/queue.arn", "/omni-wt-rt-updates/prod/tracking-notes/queue.arn"]
sqs_deadletter_queue_arn_ssm_name = ["/omni-wt-rt-updates/prod/shipment-header/DLQ.arn", "/omni-wt-rt-updates/prod/shipment-apar/DLQ.arn", "/omni-wt-rt-updates/prod/references/DLQ.arn", "/omni-wt-rt-updates/prod/shipper/DLQ.arn", "/omni-wt-rt-updates/prod/consignee/DLQ.arn", "/omni-wt-rt-updates/prod/shipment-milestone/DLQ.arn", "/omni-wt-rt-updates/prod/apar-failure/DLQ.arn", "/omni-wt-rt-updates/prod/shipment-desc/DLQ.arn", "/omni-wt-rt-updates/prod/customers/DLQ.arn", "/omni-wt-rt-updates/prod/instructions/DLQ.arn", "/omni-wt-rt-updates/prod/users/DLQ.arn", "/omni-wt-rt-updates/prod/charge-cost-code/DLQ.arn", "/omni-wt-rt-updates/prod/consol-stop-items/DLQ.arn", "/omni-wt-rt-updates/prod/consol-stop-headers/DLQ.arn", "/omni-wt-rt-updates/prod/confirmation-cost/DLQ.arn", "/omni-wt-rt-updates/prod/zip-codes/DLQ.arn", "/omni-wt-rt-updates/prod/timezone-master/DLQ.arn", "/omni-wt-rt-updates/prod/timezone-zip-cr/DLQ.arn", "/omni-wt-rt-updates/prod/tracking-notes/DLQ.arn"]
sqs_queue_url_ssm_name            = ["/omni-wt-rt-updates/prod/shipment-header/queue.url", "/omni-wt-rt-updates/prod/shipment-apar/queue.url", "/omni-wt-rt-updates/prod/references/queue.url", "/omni-wt-rt-updates/prod/shipper/queue.url", "/omni-wt-rt-updates/prod/consignee/queue.url", "/omni-wt-rt-updates/prod/shipment-milestone/queue.url", "/omni-wt-rt-updates/prod/apar-failure/queue.url", "/omni-wt-rt-updates/prod/shipment-desc/queue.url", "/omni-wt-rt-updates/prod/customers/queue.url", "/omni-wt-rt-updates/prod/instructions/queue.url", "/omni-wt-rt-updates/prod/users/queue.url", "/omni-wt-rt-updates/prod/charge-cost-code/queue.url", "/omni-wt-rt-updates/prod/consol-stop-items/queue.url", "/omni-wt-rt-updates/prod/consol-stop-headers/queue.url", "/omni-wt-rt-updates/prod/confirmation-cost/queue.url", "/omni-wt-rt-updates/prod/zip-codes/queue.url", "/omni-wt-rt-updates/prod/timezone-master/queue.url", "/omni-wt-rt-updates/prod/timezone-zip-cr/queue.url", "/omni-wt-rt-updates/prod/tracking-notes/queue.url"]
sqs_deadletter_queue_url_ssm_name = ["/omni-wt-rt-updates/prod/shipment-header/DLQ.url", "/omni-wt-rt-updates/prod/shipment-apar/DLQ.url", "/omni-wt-rt-updates/prod/references/DLQ.url", "/omni-wt-rt-updates/prod/shipper/DLQ.url", "/omni-wt-rt-updates/prod/consignee/DLQ.url", "/omni-wt-rt-updates/prod/shipment-milestone/DLQ.url", "/omni-wt-rt-updates/prod/apar-failure/DLQ.url", "/omni-wt-rt-updates/prod/shipment-desc/DLQ.url", "/omni-wt-rt-updates/prod/customers/DLQ.url", "/omni-wt-rt-updates/prod/instructions/DLQ.url", "/omni-wt-rt-updates/prod/users/DLQ.url", "/omni-wt-rt-updates/prod/charge-cost-code/DLQ.url", "/omni-wt-rt-updates/prod/consol-stop-items/DLQ.url", "/omni-wt-rt-updates/prod/consol-stop-headers/DLQ.url", "/omni-wt-rt-updates/prod/confirmation-cost/DLQ.url", "/omni-wt-rt-updates/prod/zip-codes/DLQ.url", "/omni-wt-rt-updates/prod/timezone-master/DLQ.url", "/omni-wt-rt-updates/prod/timezone-zip-cr/DLQ.url", "/omni-wt-rt-updates/prod/tracking-notes/DLQ.url"]
s3_notification_table_name        = ["tbl_ShipmentHeader", "tbl_ShipmentAPAR", "tbl_References", "tbl_Shipper", "tbl_Consignee", "tbl_ShipmentMilestone", "tbl_APARFailure", "tbl_ShipmentDesc", "tbl_Customers", "tbl_Instructions", "tbl_Users", "tbl_ChargeCostCode", "tbl_ConsolStopItems", "tbl_ConsolStopHeaders", "tbl_ConfirmationCost", "tbl_ZipCodes", "tbl_TimeZoneMaster", "tbl_TimeZoneZipCR", "tbl_TrackingNotes"]
security_group_id                 = "sg-bbb640df"
subnet_A_id                       = "subnet-36338841"
subnet_B_id                       = "subnet-65e1443c"
omni_shipment_header_arn          = "arn:aws:sns:us-east-1:332281781429:omni-wt-rt-shipment-header-prod"
omni_references_arn               = "arn:aws:sns:us-east-1:332281781429:omni-wt-rt-references-prod"
omni_shipper_arn                  = "arn:aws:sns:us-east-1:332281781429:omni-wt-rt-shipper-prod"
omni_consignee_arn                = "arn:aws:sns:us-east-1:332281781429:omni-wt-rt-consignee-prod"
omni_shipment_milestone_arn       = "arn:aws:sns:us-east-1:332281781429:omni-wt-rt-shipment-milestone-prod"
omni_shipment_apar_arn            = "arn:aws:sns:us-east-1:332281781429:omni-wt-rt-shipment-apar-prod"
omni_apar_failure_arn             = "arn:aws:sns:us-east-1:332281781429:omni-wt-rt-apar-failure-prod"
omni_toyota_arn                   = "arn:aws:sqs:us-east-1:332281781429:omni-rt-toyota-prod"
omni_toyota_url                   = "https://sqs.us-east-1.amazonaws.com/332281781429/omni-rt-toyota-prod"
omni_toyota_dlq_arn               = "arn:aws:sqs:us-east-1:332281781429:omni-rt-toyota-DLQ-prod"
omni_toyota_dlq_url               = "https://sqs.us-east-1.amazonaws.com/332281781429/omni-rt-toyota-DLQ-prod"
shipment_desc_sns_arn             = "arn:aws:sns:us-east-1:332281781429:omni-wt-rt-shipment-desc-prod"
instructions_sns_arn              = "arn:aws:sns:us-east-1:332281781429:omni-wt-rt-instructions-prod"
consol_stop_items_sns_arn         = "arn:aws:sns:us-east-1:332281781429:omni-wt-rt-consol-stop-items-prod"
consol_stop_headers_sns_arn       = "arn:aws:sns:us-east-1:332281781429:omni-wt-rt-consol-stop-headers-prod"
confirmation_cost_sns_arn         = "arn:aws:sns:us-east-1:332281781429:omni-wt-rt-confirmation-cost-prod"
zip_codes_sns_arn                 = "arn:aws:sns:us-east-1:332281781429:omni-wt-rt-zip-codes-prod"
timezone_master_sns_arn           = "arn:aws:sns:us-east-1:332281781429:omni-wt-rt-timezone-master-prod"
timezone_zip_cr_sns_arn           = "arn:aws:sns:us-east-1:332281781429:omni-wt-rt-timezone-zip-cr-prod"
tracking_notes_sns_arn            = "arn:aws:sns:us-east-1:332281781429:omni-wt-rt-tracking-notes-prod"
ref_orderNo_index                 = "omni-wt-rt-ref-orderNo-index-prod"
instructions_orderNo_index        = "omni-wt-instructions-orderNo-index-prod"
confirmation_cost_orderNo_index   = "omni-wt-confirmation-cost-orderNo-index-prod"
omni_ivia_ddb_name                = "omni-rt-ivia-prod"
# omni_ivia_createShipment_url                = "https://uat-api.dev.ivia.us/v2/shipments/uncovered" TODO
# omni_ivia_createShipment_token              = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJvY2N1cnJlZF9vbiI6MTY3OTA0Njk1MjU1NSwidXNlcl9pZCI6MTAwMzk3NSwib3JnX2lkIjoxMDA0NDUxLCJwZXJtaXNzaW9ucyI6W251bGxdLCJzY29wZSI6WyJhcGkiXSwib3Blbl9hcGlfaWQiOiJkNDM2NGRhYy05ZGRhLTRmZDUtYWYyYS04ZGNmYTVjMjA5MzUiLCJvcGVuX2FwaV91c2VyX2lkIjoxMDA0MzY1LCJleHAiOjI2NzkwNDY5NTEsInJlZ2lvbiI6Ik5BIiwianRpIjoiZGVmMzUwYWMtM2IxMS00ZmFlLThlYTEtNGJiYjkxMGE0ZWY5IiwiY2xpZW50X2lkIjoib3Blbi1hcGkifQ.ObNVtPzX2ih6qRt2SPGb_xIQXX_lHzB47NhzHAXkKfJ4Kk70C6W0bYijZCifVDdKUclqsGUv29IhWhj3jIk0yzbGjLYq5YkYMipqh3ZS1wF_D_ehG3Rc17cuOeiY1q4Exmd8oaLU-fNDAbInkFhdqsZBf51Lh-Ytu1zCaxUnPLtLTK-9QZxVAYMnTt9nDupwrR62gsomtUSSOVQgitwpVElf7SJjvpM2_Hv30t9BkpEnXIvr9xrcOUmEg6OE3-evIUS1ymN-v23oxSbgLxoHtpDOdrpQ6BdAz-4CQdUn0U1q7qx8Q6vCf7inDWP8bJXRlKl2aP-B3ou1PWbhE-IwVw" TODO
# omni_ivia_createShipment_xmlUpdate_url      = "https://wttest.omnilogistics.com/WTKServices/AirtrakShipment.asmx" TODO
# omni_ivia_createShipment_xmlUpdate_userId   = "eeprod" TODO
# omni_ivia_createShipment_xmlUpdate_password = "eE081020!" TODO
# omni_ivia_createShipment_carrierId          = "1000025" TODO
# omni_ivia_addMilestone_url         = "https://wttest.omnilogistics.com/WTKServices/shipments.asmx" TODO
# toyota_authApi_clientId            = "a4eb2f67-3a28-450f-8af5-ae962f123d90" TODO
# toyota_authApi_url                 = "https://d1h9vb8y1s0f1d.cloudfront.net/api/JWT" TODO
# toyota_api_url                     = "https://ddvyfwjl3479f.cloudfront.net/api/ShipmentPost" TODO
omni_toyota_ddb_tablename = "omni-rt-toyota-prod"
# omni_toyota_ddb_streamArn          = "arn:aws:dynamodb:us-east-1:332281781429:table/omni-rt-toyota-prod/stream/2022-12-05T14:09:42.128" TODO
omni_toyota_response_ddb_tableName = "omni-rt-toyota-response-prod"
omni_wt_rt_updates_ivia_sqs_arn    = "arn:aws:sqs:us-east-1:332281781429:omni-rt-ivia-prod"
omni_iviaresponse_ddb_name         = "omni-rt-ivia-response-prod"
# omni_ivia_ddb_streamarn            = "arn:aws:dynamodb:us-east-1:332281781429:table/omni-rt-ivia-prod/stream/2022-12-06T19:05:20.641" TODO
shipment_header_filter_billno = "23032"
shipmentApar_filter_Vendor_Id = "T19262"

