env = "prod" //
region = "us-east-1" //
aws_account_number          = "332281781429"  //
kms_key_arn_for_dms = "arn:aws:kms:us-east-1:332281781429:key/f786e3aa-7612-40da-aafa-dd21b2ab2e1d" //
replication_subnet_group_id = "default-vpc-ed4b2288"  //
dms_vpc_security_group_id = "sg-0394c6d99a53ba9a7" //
kms_key_arn_for_dms_source = "arn:aws:kms:us-east-1:332281781429:key/f786e3aa-7612-40da-aafa-dd21b2ab2e1d" //
dms_instance_storage = 100 //
source_endpoint_arn = "arn:aws:dms:us-east-1:332281781429:endpoint:MYMJ3KPIC7ZOV7CWY6M4ZNCXXA" //
dms_instance_class = "dms.c5.2xlarge" //
dms_security_group = "sg-0394c6d99a53ba9a7" //
sqs_queue_name = ["omni-wt-rt-shipment-header-queue-prod", "omni-wt-rt-shipment-apar-queue-prod", "omni-wt-rt-references-queue-prod", "omni-wt-rt-shipper-queue-prod", "omni-wt-rt-consignee-queue-prod", "omni-wt-rt-shipment-milestone-queue-prod", "omni-wt-rt-apar-failure-queue-prod", "omni-wt-rt-shipment-desc-prod", "omni-wt-rt-customers-prod", "omni-wt-rt-instructions-prod", "omni-wt-rt-users-prod", "omni-wt-rt-charge-cost-code-prod"]
sqs_deadletter_queue_name = ["omni-wt-rt-shipment-header-DLQ-prod", "omni-wt-rt-shipment-apar-DLQ-prod", "omni-wt-rt-references-DLQ-prod", "omni-wt-rt-shipper-DLQ-prod", "omni-wt-rt-consignee-DLQ-prod", "omni-wt-rt-shipment-milestone-DLQ-prod", "omni-wt-rt-apar-failure-DLQ-prod", "omni-wt-rt-shipment-desc-DLQ-prod", "omni-wt-rt-customers-DLQ-prod", "omni-wt-rt-instructions-DLQ-prod", "omni-wt-rt-users-DLQ-prod", "omni-wt-rt-charge-cost-code-DLQ-prod"]
sqs_queue_arn_ssm_name = ["/omni-wt-rt-updates/prod/shipment-header/queue.arn", "/omni-wt-rt-updates/prod/shipment-apar/queue.arn", "/omni-wt-rt-updates/prod/references/queue.arn", "/omni-wt-rt-updates/prod/shipper/queue.arn", "/omni-wt-rt-updates/prod/consignee/queue.arn", "/omni-wt-rt-updates/prod/shipment-milestone/queue.arn", "/omni-wt-rt-updates/prod/apar-failure/queue.arn", "/omni-wt-rt-updates/prod/shipment-desc/queue.arn", "/omni-wt-rt-updates/prod/customers/queue.arn", "/omni-wt-rt-updates/prod/instructions/queue.arn", "/omni-wt-rt-updates/prod/users/queue.arn", "/omni-wt-rt-updates/prod/charge-cost-code/queue.arn"]
sqs_deadletter_queue_arn_ssm_name = ["/omni-wt-rt-updates/prod/shipment-header/DLQ.arn", "/omni-wt-rt-updates/prod/shipment-apar/DLQ.arn", "/omni-wt-rt-updates/prod/references/DLQ.arn", "/omni-wt-rt-updates/prod/shipper/DLQ.arn", "/omni-wt-rt-updates/prod/consignee/DLQ.arn", "/omni-wt-rt-updates/prod/shipment-milestone/DLQ.arn", "/omni-wt-rt-updates/prod/apar-failure/DLQ.arn", "/omni-wt-rt-updates/prod/shipment-desc/DLQ.arn", "/omni-wt-rt-updates/prod/customers/DLQ.arn", "/omni-wt-rt-updates/prod/instructions/DLQ.arn", "/omni-wt-rt-updates/prod/users/DLQ.arn", "/omni-wt-rt-updates/prod/charge-cost-code/DLQ.arn"]
sqs_queue_url_ssm_name = ["/omni-wt-rt-updates/prod/shipment-header/queue.url", "/omni-wt-rt-updates/prod/shipment-apar/queue.url", "/omni-wt-rt-updates/prod/references/queue.url", "/omni-wt-rt-updates/prod/shipper/queue.url", "/omni-wt-rt-updates/prod/consignee/queue.url", "/omni-wt-rt-updates/prod/shipment-milestone/queue.url", "/omni-wt-rt-updates/prod/apar-failure/queue.url", "/omni-wt-rt-updates/prod/shipment-desc/queue.url", "/omni-wt-rt-updates/prod/customers/queue.url", "/omni-wt-rt-updates/prod/instructions/queue.url", "/omni-wt-rt-updates/prod/users/queue.url", "/omni-wt-rt-updates/prod/charge-cost-code/queue.url"]
sqs_deadletter_queue_url_ssm_name = ["/omni-wt-rt-updates/prod/shipment-header/DLQ.url", "/omni-wt-rt-updates/prod/shipment-apar/DLQ.url", "/omni-wt-rt-updates/prod/references/DLQ.url", "/omni-wt-rt-updates/prod/shipper/DLQ.url", "/omni-wt-rt-updates/prod/consignee/DLQ.url", "/omni-wt-rt-updates/prod/shipment-milestone/DLQ.url", "/omni-wt-rt-updates/prod/apar-failure/DLQ.url", "/omni-wt-rt-updates/prod/shipment-desc/DLQ.url", "/omni-wt-rt-updates/prod/customers/DLQ.url", "/omni-wt-rt-updates/prod/instructions/DLQ.url", "/omni-wt-rt-updates/prod/users/DLQ.url", "/omni-wt-rt-updates/prod/charge-cost-code/DLQ.url"]
s3_notification_table_name = ["tbl_ShipmentHeader", "tbl_ShipmentAPAR", "tbl_References", "tbl_Shipper", "tbl_Consignee", "tbl_ShipmentMilestone", "tbl_APARFailure", "tbl_ShipmentDesc", "tbl_Customers", "tbl_Instructions", "tbl_Users", "tbl_ChargeCostCode"]
security_group_id = "sg-bbb640df"
subnet_A_id = "subnet-36338841"
subnet_B_id = "subnet-65e1443c"
omni_shipment_header_arn = "arn:aws:sns:us-east-1:332281781429:omni-wt-rt-shipment-header-prod"
omni_references_arn = "arn:aws:sns:us-east-1:332281781429:omni-wt-rt-references-prod"
omni_shipper_arn = "arn:aws:sns:us-east-1:332281781429:omni-wt-rt-shipper-prod"
omni_consignee_arn = "arn:aws:sns:us-east-1:332281781429:omni-wt-rt-consignee-prod"
omni_shipment_milestone_arn = "arn:aws:sns:us-east-1:332281781429:omni-wt-rt-shipment-milestone-prod"
omni_shipment_apar_arn = "arn:aws:sns:us-east-1:332281781429:omni-wt-rt-shipment-apar-prod"
omni_apar_failure_arn = "arn:aws:sns:us-east-1:332281781429:omni-wt-rt-apar-failure-prod"
omni_toyota_arn = "arn:aws:sqs:us-east-1:332281781429:omni-rt-toyota-prod"
omni_toyota_url = "https://sqs.us-east-1.amazonaws.com/332281781429/omni-rt-toyota-prod"
omni_toyota_dlq_arn = "arn:aws:sqs:us-east-1:332281781429:omni-rt-toyota-DLQ-prod"
omni_toyota_dlq_url = "https://sqs.us-east-1.amazonaws.com/332281781429/omni-rt-toyota-DLQ-prod"
shipment_desc_sns_arn = "arn:aws:sns:us-east-1:332281781429:omni-wt-rt-shipment-desc-prod"
instructions_sns_arn = "arn:aws:sns:us-east-1:332281781429:omni-wt-rt-instructions-prod"
ref_orderNo_index = "omni-wt-rt-ref-orderNo-index-prod"
instructions_orderNo_index = "omni-wt-instructions-orderNo-index-prod"
omni_ivia_ddb_name = "omni-rt-ivia-prod"
#omni_ivia_createShipment_url = "https://api-uat.prod.ivia.us/shipments/uncovered" //TODO - get from Ivia Team
#omni_ivia_createShipment_token = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJvY2N1cnJlZF9vbiI6MTY2NzQ3OTcwNDM0MSwidXNlcl9pZCI6MTAwMzk3NSwib3JnX2lkIjoxMDA0NDUxLCJwZXJtaXNzaW9ucyI6W251bGxdLCJzY29wZSI6WyJhcGkiXSwib3Blbl9hcGlfaWQiOiJhNzdjOTZhOS0xNDg2LTQyNzctODA2Zi0zMGIzNDc0NGI5NzEiLCJvcGVuX2FwaV91c2VyX2lkIjoxMDAzOTc2LCJleHAiOjI2Njc0Nzk3MDMsInJlZ2lvbiI6Ik5BIiwianRpIjoiYzA3ODFkMjYtZTZmOS00ZjQ4LWJlOTEtNTNjN2JkNGJhYWIzIiwiY2xpZW50X2lkIjoib3Blbi1hcGkifQ.LZurjH67TW7zX6GvRsmCygtljP4iHlmLMVT4kzO9K5eeZIj6en4hPJiSTIH7-Bd1ytpVLSE_aFwcyQa6Qsx50WOgZJWhvBynwVDTGtLqzXF-rOE_D18i7TS01OueEnGlbnSry2UV9sye1PWy_6s0SEEglZdbhf5WZKs4SU0pcUUfTkTC_Pzjg4RLHRlennS1MY44F0yV5Shococ15bOcICxtfzLE7CYY5wWCv3e1RwVFCRl3_GDsyHl1Jxp9aevX8bepItyn4alFguwgH4gmA2sG3uu4FAdUKXZ4MK85I7SwOMPeWulmMvIgcSAduhvC7ua3xl3Vz3bYmJ_yExXhAA" //TODO - get from Ivia Team
omni_ivia_createShipment_xmlUpdate_url = "https://worldtrak.omnilogistics.com/WTKServices/AirtrakShipment.asmx"
omni_ivia_createShipment_xmlUpdate_userId = "eeprod"
omni_ivia_createShipment_xmlUpdate_password = "eE081020!"
#omni_ivia_createShipment_carrierId = "1000025" //TODO - get from Ivia Team
omni_ivia_addMilestone_url = "https://worldtrak.omnilogistics.com/WTKServices/shipments.asmx"
toyota_authApi_clientId = "0b0d9576-0e16-4c81-9842-a5363e151c3e"
toyota_authApi_url = "https://d2wk2os32zeiu5.cloudfront.net/api/JWT"
toyota_api_url = "https://d3vxcvah7g5a8u.cloudfront.net/api/ShipmentPost"
omni_toyota_ddb_tablename = "omni-rt-toyota-prod"
#omni_toyota_ddb_streamArn = "arn:aws:dynamodb:us-east-1:332281781429:table/omni-rt-toyota-prod/stream/2022-12-05T14:09:42.128" //TODO - get this after Monowar deploys omni-toyota-backend to prod
omni_toyota_response_ddb_tableName = "omni-rt-toyota-response-prod"
omni_wt_rt_updates_ivia_sqs_arn = "arn:aws:sqs:us-east-1:332281781429:omni-rt-ivia-prod"
omni_iviaresponse_ddb_name = "omni-rt-ivia-response-prod"
#omni_ivia_ddb_streamarn = "arn:aws:dynamodb:us-east-1:332281781429:table/omni-rt-ivia-prod/stream/2022-12-06T19:05:20.641" //TODO - get this after Kazi deploys omni-ivia-updates to prod
shipment_header_filter_billno = "22531" 
shipmentApar_filter_Vendor_Id = "T19262" 